baseURL = "https://aml-cs.github.io/"
languageCode = "en-us"
title = "AML-CS | Uninorte"

[params]
# description = "Applied Math and Computer Science Laboratory (AML-CS) at Universidad del Norte in Barranquilla"
logoimage = "images/logo.jpg"
copyright = "Universidad del Norte, Colombia."

# mathjax = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
## Uncomment if you want mathjax enabled. The above cdn source is taken from https://gohugo.io/content-management/formats/#mathjax-with-hugo   


[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Talks"
url = "/talks/"
identifier = "talks"
  [[menu.main]]
  parent = "talks"
  weight = 1
  name = "Talk Series"
  url = "/talks/talk-series/"
  [[menu.main]]
  parent = "talks"
  weight = 2
  name = "Talks by Dr. Elias Nino-Ruiz"
  url = "/talks/elias-ni√±o/"

[[menu.main]]
weight = 3
name = "Posts"
url = "/posts/"

[[menu.main]]
weight = 4
name = "Current Students"
url = "/current-students/"

[[menu.main]]
weight = 5
name = "Former Students"
url = "/former-students/"

[[menu.main]]
weight = 6
name = "Publications"
url = "/publications/"

[[menu.main]]
weight = 7
name = "Awards"
url = "/awards/"
